In [ ]:
text = """In the near future, humanity faces extinction due to dust storms and widespread crop blights. Joseph Cooper, a widowed former NASA test pilot, works as a farmer and raises his children, Murph and Tom, alongside his father-in-law Donald. Cooper is reprimanded by Murph's teachers for telling her that the Apollo missions were not fabricated. During a dust storm, the two discover that dust patterns in Murph's room, which she had first attributed to a ghost, result from a gravitational anomaly. They translate them into geographic coordinates, which lead them to a secret NASA facility headed by Professor John Brand. He explains that 48 years earlier, a wormhole appeared near Saturn, leading to a system in another galaxy with 12 potentially habitable planets located near a black hole named Gargantua. Volunteers of the Lazarus expedition had previously traveled through the wormhole to evaluate the planets, with three — Miller, Edmunds, and Mann — reporting back desirable results.

Cooper is enlisted to pilot the Endurance spacecraft through the wormhole as part of a mission to colonize a habitable planet with 5000 frozen embryos and ensure humanity's survival. Meanwhile, Professor Brand would continue his work on solving a gravity equation whose solution would supposedly enable construction of a spacecraft for an exodus from Earth. Cooper accepts against Murph's wishes and promises to return. When she refuses to see him off, he leaves her his wristwatch to compare their relative time when he returns.

The crew, consisting of Cooper, robots TARS and CASE, and scientists Dr. Amelia Brand (Professor Brand's daughter), Romilly, and Doyle, traverse the wormhole after a two-year voyage to Saturn. Cooper, Doyle, and Brand use a lander to investigate Miller's planet, where time is severely dilated. After landing in knee-high water and finding only wreckage from Miller's expedition, a gigantic tidal wave kills Doyle and waterlogs the lander's engines.

By the time they leave the planet, Cooper and Brand discover that 23 years have elapsed on the Endurance. Having enough fuel left for only one of the other two planets, Cooper and Romilly decide to go to Mann's planet, despite Brand's protests, as he is still broadcasting. En route, they receive messages from Earth and Cooper watches Tom grow up, marry, and lose his first son. An adult Murph is now a scientist working on the gravity equation with Professor Brand. On his deathbed, Professor Brand confesses that the Endurance crew was never supposed to return, knowing that a complete solution to the equation was not feasible without observations of a gravitational singularity from inside a black hole.

On Mann's planet, they awaken him from cryostasis, and he assures them that colonization is possible, despite the extreme environment. During a scouting mission, Mann attempts to kill Cooper and reveals that he falsified his data in the hope of being rescued. He steals Cooper's lander and heads for the Endurance. While a booby trap set by Mann kills Romilly, Brand rescues Cooper with the other lander and they race back to the Endurance. Mann is killed in a failed manual docking operation, severely damaging the Endurance, but Cooper is able to regain control of the station through his own docking maneuver.

With insufficient fuel, Cooper and Brand resort to a slingshot around Gargantua, which costs them 51 years due to time dilation. In the process, Cooper and TARS jettison their landers to lighten the Endurance so that Brand and CASE may reach Edmunds' planet. Falling into Gargantua's event horizon, they eject from their craft and find themselves in a tesseract made up of infinite copies of Murph's bedroom across moments in time. Cooper deduces that the tesseract was constructed by advanced humans in the far future, and realizes that he had always been Murph's "ghost". He uses Morse code to manipulate the second hand of the wristwatch he gave her before he left, giving Murph the data that TARS collected, which enables her to complete Professor Brand's solution.

The tesseract, its purpose fulfilled, collapses before ejecting Cooper and TARS. Cooper wakes up on a station orbiting Saturn. He reunites with Murph, now elderly and on her deathbed, who tells him to seek out Brand. Cooper and TARS take a spacecraft to rejoin Brand and CASE, who are setting up the human colony on Edmunds' habitable planet."""

In [ ]:
len(text)

4407

In [ ]:
chunks = []
words = text.split(" ")

s = ""
for w in words: 
    s += w + " "
    if len(s) > 1000: 
        chunks.append(s)
        s = ""

chunks.append(s)

In [ ]:
chunks

["In the near future, humanity faces extinction due to dust storms and widespread crop blights. Joseph Cooper, a widowed former NASA test pilot, works as a farmer and raises his children, Murph and Tom, alongside his father-in-law Donald. Cooper is reprimanded by Murph's teachers for telling her that the Apollo missions were not fabricated. During a dust storm, the two discover that dust patterns in Murph's room, which she had first attributed to a ghost, result from a gravitational anomaly. They translate them into geographic coordinates, which lead them to a secret NASA facility headed by Professor John Brand. He explains that 48 years earlier, a wormhole appeared near Saturn, leading to a system in another galaxy with 12 potentially habitable planets located near a black hole named Gargantua. Volunteers of the Lazarus expedition had previously traveled through the wormhole to evaluate the planets, with three — Miller, Edmunds, and Mann — reporting back desirable results.\n\nCooper is enlisted ",
 "to pilot the Endurance spacecraft through the wormhole as part of a mission to colonize a habitable planet with 5000 frozen embryos and ensure humanity's survival. Meanwhile, Professor Brand would continue his work on solving a gravity equation whose solution would supposedly enable construction of a spacecraft for an exodus from Earth. Cooper accepts against Murph's wishes and promises to return. When she refuses to see him off, he leaves her his wristwatch to compare their relative time when he returns.\n\nThe crew, consisting of Cooper, robots TARS and CASE, and scientists Dr. Amelia Brand (Professor Brand's daughter), Romilly, and Doyle, traverse the wormhole after a two-year voyage to Saturn. Cooper, Doyle, and Brand use a lander to investigate Miller's planet, where time is severely dilated. After landing in knee-high water and finding only wreckage from Miller's expedition, a gigantic tidal wave kills Doyle and waterlogs the lander's engines.\n\nBy the time they leave the planet, Cooper ",
 "and Brand discover that 23 years have elapsed on the Endurance. Having enough fuel left for only one of the other two planets, Cooper and Romilly decide to go to Mann's planet, despite Brand's protests, as he is still broadcasting. En route, they receive messages from Earth and Cooper watches Tom grow up, marry, and lose his first son. An adult Murph is now a scientist working on the gravity equation with Professor Brand. On his deathbed, Professor Brand confesses that the Endurance crew was never supposed to return, knowing that a complete solution to the equation was not feasible without observations of a gravitational singularity from inside a black hole.\n\nOn Mann's planet, they awaken him from cryostasis, and he assures them that colonization is possible, despite the extreme environment. During a scouting mission, Mann attempts to kill Cooper and reveals that he falsified his data in the hope of being rescued. He steals Cooper's lander and heads for the Endurance. While a booby trap ",
 'set by Mann kills Romilly, Brand rescues Cooper with the other lander and they race back to the Endurance. Mann is killed in a failed manual docking operation, severely damaging the Endurance, but Cooper is able to regain control of the station through his own docking maneuver.\n\nWith insufficient fuel, Cooper and Brand resort to a slingshot around Gargantua, which costs them 51 years due to time dilation. In the process, Cooper and TARS jettison their landers to lighten the Endurance so that Brand and CASE may reach Edmunds\' planet. Falling into Gargantua\'s event horizon, they eject from their craft and find themselves in a tesseract made up of infinite copies of Murph\'s bedroom across moments in time. Cooper deduces that the tesseract was constructed by advanced humans in the far future, and realizes that he had always been Murph\'s "ghost". He uses Morse code to manipulate the second hand of the wristwatch he gave her before he left, giving Murph the data that TARS collected, which enables ',
 "her to complete Professor Brand's solution.\n\nThe tesseract, its purpose fulfilled, collapses before ejecting Cooper and TARS. Cooper wakes up on a station orbiting Saturn. He reunites with Murph, now elderly and on her deathbed, who tells him to seek out Brand. Cooper and TARS take a spacecraft to rejoin Brand and CASE, who are setting up the human colony on Edmunds' habitable planet. "]

In [ ]:
# pip install langchain-text-splitters
from langchain_text_splitters import CharacterTextSplitter

In [ ]:
splitter = CharacterTextSplitter(separator="\n", chunk_size=200, chunk_overlap=0)
chunks = splitter.split_text(text)
len(chunks)

Created a chunk of size 986, which is longer than the specified 200
Created a chunk of size 529, which is longer than the specified 200
Created a chunk of size 449, which is longer than the specified 200
Created a chunk of size 708, which is longer than the specified 200
Created a chunk of size 612, which is longer than the specified 200
Created a chunk of size 769, which is longer than the specified 200

7

In [ ]:
for c in chunks: # the size may be bigger than 200 because the splitter will split on newlines, so if there are a lot of words between newlines, the chunk size may be bigger than 200
    print(len(c))

986
529
449
708
612
769
342

In [ ]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

r_splitter = RecursiveCharacterTextSplitter(separators=["\n\n", "\n", " ", ""], chunk_size=200, chunk_overlap=0)
r_chunks = r_splitter.split_text(text)
len(r_chunks)

25

In [ ]:
for c in r_chunks: 
    print(len(c))

200
199
194
197
192
193
194
140
192
197
58
197
199
199
110
194
195
199
21
198
192
195
181
197
144

In [ ]:
chunks = text.split("\n\n") # use the first separator 
for c in chunks:
    print(len(c))

986
529
449
708
612
769
342

In [ ]:
197 + 144

341

In [ ]:
chunks[-1]

"The tesseract, its purpose fulfilled, collapses before ejecting Cooper and TARS. Cooper wakes up on a station orbiting Saturn. He reunites with Murph, now elderly and on her deathbed, who tells him to seek out Brand. Cooper and TARS take a spacecraft to rejoin Brand and CASE, who are setting up the human colony on Edmunds' habitable planet."

In [ ]:
sec_chunks = chunks[-1].split("\n") # use the second separator
for c in sec_chunks: # still greater than 200 => continue to split on the next separator
    print(len(c))

342

In [ ]:
third_chunks = sec_chunks[-1].split(" ") # use the third separator => then merged, optimized for the chunk size: 197 + 144
for c in third_chunks:
    print(len(c))

3
10
3
7
10
9
6
8
6
3
5
6
5
2
2
1
7
8
7
2
8
4
6
3
7
3
2
3
9
3
5
3
2
4
3
6
6
3
4
4
1
10
2
6
5
3
5
3
3
7
2
3
5
6
2
8
9
7

In [ ]:
import pandas as pd 

pd.set_option('display.max_colwidth', 100)

In [ ]:
df = pd.read_csv("data/sample_text.csv")
df.shape

(8, 2)

In [ ]:
df

                                                text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [ ]:
from sentence_transformers import SentenceTransformer # pip install ipywidgets 
import os 
from dotenv import load_dotenv
load_dotenv()

True

In [ ]:
api_key = os.getenv("HUGGINGFACEHUB_API_TOKEN")

In [ ]:
encoder = SentenceTransformer("all-mpnet-base-v2", token=api_key)
encoder.encode

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3442.97it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

<bound method SentenceTransformer.encode of SentenceTransformer(
  (0): Transformer({'max_seq_length': 384, 'do_lower_case': False, 'architecture': 'MPNetModel'})
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)>

In [ ]:
vectors = encoder.encode(df.text)
vectors.shape # embedding dim of transformer models is usually 768, but it can be different depending on the model used

(8, 768)

In [ ]:
dim = vectors.shape[1]

In [ ]:
import faiss

In [ ]:
index = faiss.IndexFlatL2(dim) # index will use L2 distance to calculate the similarity between vectors, but there are other options such as inner product (IP) or cosine similarity (COSINE) depending on the use case. L2 is commonly used for dense vector search, while IP and COSINE are often used for sparse vector search. 
index.reset() # or rest first 
index.add(vectors) # need to run the above cell to reset the index before adding to avoid duplicates
print(index.ntotal) # number of vectors in the index

8

In [ ]:
search_query = "I want to buy a polo t-shirt"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [ ]:
vec = vec.reshape(1,-1) 
vec.shape

(1, 768)

In [ ]:
# return the top 2 most similar vectors to the search query, along with their distances. The smaller the distance, the more similar the vectors are.
# The output will be a tuple of two arrays: the first array contains the distances of the nearest neighbors, and the second array contains the indices of the nearest neighbors in the original dataset.
distances, I = index.search(vec, k=2)

In [ ]:
I

array([[3, 2]])

In [82]:
df.loc[I[0]]

                                                text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion